"""partisans

Revision ID: 0a484d4b900f
Revises: bbbc9f3626b4
Create Date: 2020-10-15 01:39:50.685827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a484d4b900f'
down_revision = 'bbbc9f3626b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partisans',
    sa.Column('partisans_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_qui_est_suivi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partisans_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_qui_est_suivi_id'], ['utilisateur.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partisans')
    # ### end Alembic commands ###
