"""table publications

Revision ID: 3de09badd5ec
Revises: a5b4ab48cf03
Create Date: 2020-09-10 11:02:44.908052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de09badd5ec'
down_revision = 'a5b4ab48cf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corps', sa.String(length=140), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_horodatage'), 'publication', ['horodatage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_horodatage'), table_name='publication')
    op.drop_table('publication')
    # ### end Alembic commands ###
