"""table Utilisateurs

Revision ID: a5b4ab48cf03
Revises: 
Create Date: 2020-09-10 09:28:52.714377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b4ab48cf03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('courriel', sa.String(length=120), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_courriel'), 'utilisateur', ['courriel'], unique=True)
    op.create_index(op.f('ix_utilisateur_nom'), 'utilisateur', ['nom'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_nom'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_courriel'), table_name='utilisateur')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
