"""dernier_acces

Revision ID: bbbc9f3626b4
Revises: bfae7a4f15cf
Create Date: 2020-09-20 23:42:30.364805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbc9f3626b4'
down_revision = 'bfae7a4f15cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('dernier_acces', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'dernier_acces')
    # ### end Alembic commands ###
